### ISSUE TITLE
Bug: jq not installed

### ISSUE THREAD

**Issue by yamatt** [ft-circleci-orbs/doppler-circleci-orb#23]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Orb version

1.5.4

### Current behavior

Using the Python environment in CircleCI, if I run `doppler/install` I get the following output:

```
Installing Doppler CLI ...
Downloading Doppler CLI
Verifying signature
Doppler CLI saved to ./doppler
Doppler ClI installed.

Installing jq ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package jq
jq installed.
```

Then when I run `doppler-circleci/load_secrets` I get this error:

```
/bin/bash: line 8: jq: command not found
/bin/bash: line 9: jq: command not found

Exited with code exit status 127
```

### Minimum reproduction config

```
orbs:
  python: circleci/python@3.1.0
  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.5.4

executors:
  main:
    docker:
      - image: python:3.11.4

commands:
  doppler_set_up:
    steps:
      - checkout
      - doppler-circleci/install
      - doppler-circleci/load_secrets

jobs:
  test:
    executor: main
    steps:
      - doppler_set_up
```

### Other

From exploring the machine itself over ssh, the reason is that the apt cache is empty. So you need to run `apt-get update` before the `apt-get install jq` command.

The other way of looking at this is the image we are using as the executor is a minimal image from Python which we could swap out to something from CircleCI.
